add a smart hint helper function to notify user
et2010/org-edit-latex pull request #10
Opened 2017-08-13 06:54 UTC by stardiviner

This helper function will auto show a message in echo-area when user move point on latex fragement or latex environment.

2017-08-15 13:34 UTC, et2010 commented
Thanks! I like your idea but I'm not very fond of adding functions to `post-command-hook` globally. Maybe the `define-minor-mode` form is a better place to go?

2017-08-15 14:22 UTC, et2010 requested changes

2017-08-15 14:22 UTC, et2010 commented on org-edit-latex.el
> +               (org-inside-LaTeX-fragment-p)))
`org-inside-LaTeX-fragment`, which is designed to be used with cdlatex. returns a non-nil value whenever the cursor is behind a `$`, `\(` or `\[`, even it is not closed yet.  Unlike cdlatex, `org-edit-latex` depends on `org-element` api heavily.

In short, this line could cause an issue. On the other hand, line 303 looks good.

2017-08-16 05:39 UTC, stardiviner commented on org-edit-latex.el
> +               (org-inside-LaTeX-fragment-p)))
You're right, a minor mode is better. I will update my code. Thanks your review.

2017-08-16 06:11 UTC, stardiviner commented on org-edit-latex.el
> +               (org-inside-LaTeX-fragment-p)))
BTW, can `org-edit-latex` support this inline style LaTeX fragment? Hope can add support for this.

2017-08-16 06:34 UTC, stardiviner commented
I updated my code, please review it. Thanks.

2017-08-16 06:58 UTC, et2010 approved these changes

2017-08-16 06:59 UTC, merged

2017-08-16 06:59 UTC, et2010 commented
Merged. Thanks!